version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription-financer
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postresql/data

volumes:
  db:
    driver: local
